values:
  pulumiConfig:
    awsRegion: us-east-1  # Different region for production
    bucketPrefix: prod-esc-
    dbPassword:
      secure: AAABAMnoPQrVZ8JfDa1/MzLpoiXmHJa7f3GtRDJtYJNUe6Ff==
    dbInstanceClass: db.t3.medium  # Larger instance for production
